[package]
name = "fate-set-commands"
version = "0.1.0"
edition = "2024"

[dependencies]
fate = { path = "../"}
twilight-http = "0.17"
rustls = "0.23"
tokio = { version = "1", features = ["full"] }
anyhow = "1"
